#!/bin/bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter nbextension      enable --py widgetsnbextension

cp -r materialscloud /srv/conda/envs/notebook/share/jupyter/voila/templates/.
